import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import type { Finding } from "../core/finding.js";
import type { ScanReport } from "../core/types.js";
import { sanitizeScanReport, severityOrder } from "./helpers.js";
import type { Reporter } from "./reporter.js";

const escapeHtml = (value: string): string => {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
};

export class HtmlReporter implements Reporter {
  generate(report: ScanReport): string {
    const sanitizedReport = sanitizeScanReport(report);
    const summaryItems = severityOrder
      .map((severity) => {
        return `<li><strong>${escapeHtml(severity)}:</strong> ${sanitizedReport.summary.findingsBySeverity[severity] ?? 0}</li>`;
      })
      .join("");

    const groupedFindings = severityOrder
      .map((severity) => {
        const findings = sanitizedReport.findings.filter(
          (finding) => finding.severity === severity
        );

        if (findings.length === 0) {
          return "";
        }

        return `
          <section class="severity-group">
            <h2>${escapeHtml(severity.toUpperCase())}</h2>
            ${findings.map((finding) => this.renderFinding(finding)).join("")}
          </section>
        `;
      })
      .join("");

    const findingsSection =
      sanitizedReport.findings.length === 0
        ? "<p class=\"empty-state\">No findings detected.</p>"
        : groupedFindings;

    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>API Security Scan Report</title>
    <style>
      :root {
        color-scheme: light;
        --bg: #f5f7fb;
        --panel: #ffffff;
        --text: #172033;
        --muted: #5d6b87;
        --border: #d7dfef;
        --accent: #0b57d0;
        --critical: #8b1e3f;
        --high: #b54708;
        --medium: #c27c00;
        --low: #2563eb;
        --info: #4b5563;
      }

      * { box-sizing: border-box; }
      body {
        margin: 0;
        padding: 32px;
        font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
        background: linear-gradient(180deg, #f8fbff 0%, var(--bg) 100%);
        color: var(--text);
      }

      main {
        max-width: 1040px;
        margin: 0 auto;
      }

      h1, h2, h3, p { margin-top: 0; }

      .panel {
        background: var(--panel);
        border: 1px solid var(--border);
        border-radius: 16px;
        padding: 24px;
        box-shadow: 0 16px 40px rgba(23, 32, 51, 0.08);
      }

      .panel + .panel,
      .severity-group + .severity-group {
        margin-top: 24px;
      }

      .meta {
        color: var(--muted);
        display: grid;
        gap: 8px;
        margin-top: 16px;
      }

      .summary-grid {
        display: grid;
        gap: 16px;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        margin-top: 20px;
      }

      .summary-card {
        background: #f8fbff;
        border: 1px solid var(--border);
        border-radius: 12px;
        padding: 16px;
      }

      .summary-card strong {
        display: block;
        font-size: 1.75rem;
        margin-bottom: 6px;
      }

      ul {
        margin: 0;
        padding-left: 20px;
      }

      .finding {
        border: 1px solid var(--border);
        border-left-width: 6px;
        border-radius: 12px;
        padding: 16px;
        margin-top: 16px;
        background: #fcfdff;
      }

      .finding.critical { border-left-color: var(--critical); }
      .finding.high { border-left-color: var(--high); }
      .finding.medium { border-left-color: var(--medium); }
      .finding.low { border-left-color: var(--low); }
      .finding.info { border-left-color: var(--info); }

      .finding-meta {
        color: var(--muted);
        font-size: 0.95rem;
        margin-bottom: 12px;
      }

      .finding dl {
        display: grid;
        grid-template-columns: 140px 1fr;
        gap: 8px 12px;
        margin: 0;
      }

      .finding dt {
        font-weight: 600;
      }

      .empty-state {
        color: var(--muted);
      }
    </style>
  </head>
  <body>
    <main>
      <section class="panel">
        <h1>API Security Scan Report</h1>
        <p>Unified artifact generated by ${escapeHtml(sanitizedReport.metadata.toolName)}.</p>
        <div class="meta">
          <div><strong>Report version:</strong> ${escapeHtml(sanitizedReport.metadata.reportVersion)}</div>
          <div><strong>Generated at:</strong> ${escapeHtml(sanitizedReport.metadata.generatedAt)}</div>
        </div>
        <div class="summary-grid">
          <div class="summary-card">
            <strong>${sanitizedReport.summary.endpointsScanned}</strong>
            <span>Endpoints scanned</span>
          </div>
          <div class="summary-card">
            <strong>${sanitizedReport.summary.totalFindings}</strong>
            <span>Total findings</span>
          </div>
          <div class="summary-card">
            <strong>By severity</strong>
            <ul>${summaryItems}</ul>
          </div>
        </div>
      </section>
      <section class="panel">
        <h2>Findings</h2>
        ${findingsSection}
      </section>
    </main>
  </body>
</html>`;
  }

  render(report: ScanReport): void {
    process.stdout.write(`${this.generate(report)}\n`);
  }

  async write(report: ScanReport, filePath: string): Promise<void> {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, this.generate(report), "utf8");
  }

  private renderFinding(finding: Finding): string {
    return `
      <article class="finding ${escapeHtml(finding.severity)}">
        <h3>${escapeHtml(finding.title)} [${escapeHtml(finding.ruleId)}]</h3>
        <p class="finding-meta">${escapeHtml(finding.method)} ${escapeHtml(finding.endpoint)}</p>
        <dl>
          <dt>Description</dt>
          <dd>${escapeHtml(finding.description)}</dd>
          <dt>Evidence</dt>
          <dd>${escapeHtml(finding.evidence)}</dd>
          <dt>Risk</dt>
          <dd>${escapeHtml(finding.risk)}</dd>
          <dt>Remediation</dt>
          <dd>${escapeHtml(finding.remediation)}</dd>
          <dt>Timestamp</dt>
          <dd>${escapeHtml(finding.timestamp)}</dd>
        </dl>
      </article>
    `;
  }
}

export const createHtmlReporter = (): HtmlReporter => {
  return new HtmlReporter();
};
